# Generated by Django 4.2.7 on 2023-12-07 17:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import soutenance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', soutenance.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_mail', models.EmailField(max_length=254, unique=True)),
                ('nom_utilisateur', models.CharField(max_length=255, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'SuperAdmin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vacataire', 'Vacataire'), ('plein', 'Plein')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('theme', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_heure', models.DateTimeField()),
                ('par_etudiant', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3)),
                ('id_enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.enseignant')),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.etudiant')),
                ('id_groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Encadreur', 'Encadreur'), ('Superviseur', 'Superviseur')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatutNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('vue', 'Vue'), ('nonvue', 'Non vue')], max_length=255)),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.etudiant')),
                ('id_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.notification')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('annee', models.IntegerField()),
                ('max_groupe', models.IntegerField()),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='RoleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.enseignant')),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.role')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.session')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('tache', models.CharField(max_length=255)),
                ('periode', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.session')),
            ],
        ),
        migrations.CreateModel(
            name='GroupeEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.enseignant')),
                ('id_groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.groupe')),
            ],
        ),
        migrations.AddField(
            model_name='groupe',
            name='id_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.session'),
        ),
        migrations.CreateModel(
            name='EtudiantGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.etudiant')),
                ('id_groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.groupe')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.session')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='id_niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.niveau'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DocumentGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('word', 'Word'), ('excel', 'Excel')], max_length=10)),
                ('url', models.URLField()),
                ('id_groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('datePosted', models.CharField(default='', max_length=20)),
                ('timePosted', models.CharField(default='', max_length=20)),
                ('category', models.CharField(max_length=300)),
                ('content', ckeditor.fields.RichTextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
