# Generated by Django 4.1.7 on 2023-11-30 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_mail', models.EmailField(max_length=254, unique=True)),
                ('nom_utilisateur', models.CharField(max_length=255, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'SuperAdmin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('sexe', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_de_naissance', models.DateField()),
                ('type', models.CharField(choices=[('vacataire', 'Vacataire'), ('plein', 'Plein')], max_length=10)),
                ('adresse', models.TextField()),
                ('numero_telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('sexe', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_de_naissance', models.DateField()),
                ('adresse', models.TextField()),
                ('numero_telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('theme', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_heure', models.DateTimeField()),
                ('par_etudiant', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3)),
                ('id_enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.enseignant')),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.etudiant')),
                ('id_groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='StatutNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('vue', 'Vue'), ('nonvue', 'Non vue')], max_length=255)),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.etudiant')),
                ('id_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.notification')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('annee', models.IntegerField()),
                ('max_groupe', models.IntegerField()),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('tache', models.CharField(max_length=255)),
                ('periode', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.session')),
            ],
        ),
        migrations.CreateModel(
            name='GroupeEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.enseignant')),
                ('id_groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.groupe')),
            ],
        ),
        migrations.AddField(
            model_name='groupe',
            name='id_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.session'),
        ),
        migrations.CreateModel(
            name='EtudiantGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.etudiant')),
                ('id_groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.groupe')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.session')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='id_niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.niveau'),
        ),
        migrations.CreateModel(
            name='DocumentGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('word', 'Word'), ('excel', 'Excel')], max_length=10)),
                ('url', models.URLField()),
                ('id_groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('word', 'Word'), ('excel', 'Excel')], max_length=255)),
                ('url', models.URLField()),
                ('visibilite', models.CharField(choices=[('tous_le_monde', 'Tous le monde'), ('enseignants_session', 'Enseignants de la session'), ('seul', 'Seul')], max_length=20)),
                ('id_enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soutenance.enseignant')),
            ],
        ),
    ]
